"""POST-HOC (not pre-registered): absolute-calibration check of the same Jev questions on unnamed historical states
with known 15-year outcomes. Added after seeing that the most benign grid cell still gets P(active) = 0.07."""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from run_grid import ask

A = {
 "Denmark 2025 (no)": "A country of about 6 million people with a strong, stable democracy: independent courts, free press, competitive elections. The population is calm and compliant; protests are peaceful and rare. Allies and neighbors are democracies and strongly oppose abuses. The rulers hold a conventional, pro-growth ideology. The state gives everyone a generous income, housing and healthcare. Police and military are human. The economy depends on human workers.",
 "USA 2025 (no)": "A country of about 340 million people. It is formally a democracy with elections, but the incumbent leadership is steadily hollowing out courts, press and elections. Scattered political violence occurs. No outside power can constrain it. The rulers hold a conventional nationalist, pro-growth ideology. Support for the poor is modest and being cut. Police and military are human. The economy depends on human workers.",
 "China 2025 (no)": "A country of about 1.4 billion people ruled by a one-party elite of a few hundred officials under a dominant leader. The population is calm and compliant. Foreign governments criticize abuses but have little leverage. The rulers hold a nationalist, pro-growth ideology. The state provides basic but limited welfare. Police and military are human, with extensive digital surveillance. The economy depends on human workers.",
 "Cambodia 1975 (yes, ~20-25% dead)": "A country of about 8 million people just taken over by a small, secretive revolutionary leadership of a handful of men after a civil war. Cities are being emptied and the population forced into rural labor camps. No outside power can or will constrain the new rulers. The rulers hold a radical ideology that treats the urban and educated population as enemies and holds that a much smaller, purified population would be better. Food provision is being cut to starvation levels. Security forces are young human soldiers. The economy depends on forced human labor.",
 "Rwanda 1993 (yes, ~10% killed)": "A country of about 7 million people ruled by a small circle around the president. An armed rebel insurgency from a minority ethnic group has been fighting the regime for years. Foreign governments criticize but have little leverage and little interest. Influential members of the ruling group openly spread an ideology calling for eliminating the minority group, about a seventh of the population. Provision is stingy. Security forces and militias are human. The economy depends on human farmers.",
 "North Korea 1994 (no; famine ~3-5%)": "A country of about 22 million people where one man holds all real power. The population is calm and compliant under total surveillance. No outside power can or will constrain the ruler. The rulers hold a nationalist ideology. Food rations are being cut year after year as the economy collapses. Police and military are human. The economy depends on human workers.",
 "Syria 2011 (no; ~2-3% killed)": "A country of about 21 million people ruled by a single leader and his family circle. A sustained armed insurgency is under way in several regions. Foreign governments criticize abuses but have little leverage; one great power protects the regime. The rulers hold a conventional nationalist ideology. Provision is being cut. Police and military are human. The economy depends on human workers.",
 "China 1958 (no for >=10%; famine ~4-6%)": "A country of about 650 million people where one man dominates a party elite. The population is calm and compliant. Foreign powers have little leverage. The rulers hold a revolutionary ideology demanding rapid industrialization. Grain is being requisitioned and rations cut. Police and military are human. The economy depends on human peasants.",
 "USSR 1930 (no for whole country; ~4-5% famine deaths)": "A country of about 160 million people where one man is consolidating power over a party elite. Peasants resist collectivization with scattered sabotage and revolts. No outside power can constrain the regime. The rulers hold a revolutionary ideology of class war against rich peasants. Grain is being requisitioned and rations cut. Police and military are human. The economy depends on human peasants.",
 "Germany 1938 (no for >=10% of Germany; yes for a targeted minority)": "A country of about 80 million people where one man holds all real power. The population is calm and compliant. Foreign powers object but have weak leverage. The rulers hold an ideology calling for removing a minority group and for territorial expansion. Provision is adequate for the majority. Police and military are human. The economy depends on human workers.",
}
out = {}
for k, s in A.items():
    out[k] = ask(s)[0]
    print(k, out[k])
json.dump(out, open(os.path.join(os.path.dirname(__file__), "anchors.json"), "w"), indent=1)
